### ISSUE TITLE
Data input field in Safari

### ISSUE THREAD

**Issue by valentinavolgina2** [valentinavolgina2/sunny-hikes#15]
data input field doesn't have format validation. Must be yyyy-mm-dd

**Comment by valentinavolgina2** [comment]
https://stackoverflow.com/questions/35682138/html5-date-picker-doesnt-show-on-safari

**Comment by ybalenko** [comment]
- [ ] Fix
- [ ] Test

**Comment by ybalenko** [comment]
Added error message. It resolved the problem.
