### ISSUE TITLE
Make a user-friendly handling for empty review form.

### ISSUE THREAD

**Issue by ybalenko** [valentinavolgina2/sunny-hikes#16]
Steps:
1. Go to the website 
2. Login
3. Select a recreation
4. Click on edit
5. Scroll down to review
6. Select 5 stars for a review/ or leave an empty
7. Click on Submit

**Actual result:** The user gets an empty page with an error: '"review.body" is not allowed to be empty'
**Expected result:** The user stays on a page and gets a notification that the review is required - TBD. We need to discuss whether we are ok with submitting only stars for example.
![img](https://user-images.githubusercontent.com/58673729/112925611-fef00800-90c6-11eb-8238-4e1ef82d88ea.png)

**Comment by valentinavolgina2** [comment]
Fixed
