### ISSUE TITLE
Inaccurate date for a posted review

### ISSUE THREAD

**Issue by ybalenko** [valentinavolgina2/sunny-hikes#17]
Steps:

1. Go to the website
2. Login
3. Select a recreation
4. Scroll down to review
5. Into the 'leave a review' form type a text
6. Click on Submit

**Actual result:** The user gets a review posted and dated by tomorrow's date.
![comment date is inaccurate](https://user-images.githubusercontent.com/58673729/112926527-69ee0e80-90c8-11eb-94ab-f77ea9dd99e8.png)

**Expected result:** The user gets a review posted and dated by their timezone time.

**Comment by ybalenko** [comment]
- [ ] Fix
- [ ] Test

**Comment by valentinavolgina2** [comment]
Fixed
