### ISSUE TITLE
Clicking on "Find" adds one more + to the link.

### ISSUE THREAD

**Issue by ybalenko** [valentinavolgina2/sunny-hikes#21]
Each time the user clicks on the 'Find' button, one more '+' is added to the link (after WA before distance). 
I am not sure it's ok. Please, check this.

https://warm-river-49749.herokuapp.com/hikes?location=Seattle+WA++++++++&distance=250&date=1617001200000

**Comment by valentinavolgina2** [comment]
Fixed
