### ISSUE TITLE
[Cosmetic] 'nafanya' detected

### ISSUE THREAD

**Issue by ybalenko** [valentinavolgina2/sunny-hikes#22]
Please check 'nafanya' is removed: local storage "tokenU":"vallnafanya"

**Comment by valentinavolgina2** [comment]
When exactly do you see "local storage "tokenU":"vallnafanya""?

**Comment by ybalenko** [comment]
![IMG](https://user-images.githubusercontent.com/58673729/113091130-24047980-91a0-11eb-8d50-3728a92c9a83.png)

**Comment by valentinavolgina2** [comment]
Fixed
