### ISSUE TITLE
Home and footer images - reduce file size without quality degradation

### ISSUE THREAD

**Issue by ybalenko** [valentinavolgina2/sunny-hikes#23]
Is it possible to reduce the sizes of the images (Home and Footer) without quality degradation? Now they are 3 Mb and 1,6 Mb. 

![images](https://user-images.githubusercontent.com/58673729/112932747-54321680-90d3-11eb-870c-6cf79bfbe17d.png)

**Comment by valentinavolgina2** [comment]
Fixed
