### ISSUE TITLE
Date of the trip: discuss input requirements

### ISSUE THREAD

**Issue by ybalenko** [valentinavolgina2/sunny-hikes#24]
1. Could it be in the past? If so, how far? For example, 1990-02-02
2. Could it be in the future?  If so, how far? For example, 2027-02-02
3. Are we going to handle invalid inputs? e.g. see images (Chrome recalculate dates, Safari can display NaN)

![chrome](https://user-images.githubusercontent.com/58673729/112933429-af183d80-90d4-11eb-8377-88a432bbe491.jpeg)
![safari-NaN](https://user-images.githubusercontent.com/58673729/112933433-b17a9780-90d4-11eb-9c8b-6c3b125095cd.png)

**Comment by valentinavolgina2** [comment]
Fixed

**Comment by ybalenko** [comment]
Added error message. It resolved the problem.
