### ISSUE TITLE
Don't have a login? Register

### ISSUE THREAD

**Issue by ybalenko** [valentinavolgina2/sunny-hikes#27]
There are 2 pages that require user registration: 'Recreations - Create new' and 'Login'.
I assume they need an additional option such as: Don't have a login? Sign Up/Register <here>

Below are an example and the actual page.

![example](https://user-images.githubusercontent.com/58673729/114231396-441a0280-992f-11eb-9715-42f36e356537.png)
![page](https://user-images.githubusercontent.com/58673729/114231402-45e3c600-992f-11eb-9a65-cfbc878b3f6d.png)

**Comment by valentinavolgina2** [comment]
done
