### ISSUE TITLE
Logged-in user: clicking on 'Login', gets a login page.

### ISSUE THREAD

**Issue by ybalenko** [valentinavolgina2/sunny-hikes#29]
Precondition:
The user has been already logged in.
Steps:
1. Go to the Home page 
2. Click on Login

Actual result: Logged-in user gets a login page with empty fields to enter.
Expected result: Do not show 'Login' and 'Register' for logged-in users.

![login](https://user-images.githubusercontent.com/58673729/114234428-93623200-9933-11eb-828e-7b0ab72e84f7.png)

**Comment by ybalenko** [comment]
- [ ] Fix
- [ ] Test

**Comment by valentinavolgina2** [comment]
Fixed

**Comment by ybalenko** [comment]
Now looks good!
