### ISSUE TITLE
server date issue

### ISSUE THREAD

**Issue by valentinavolgina2** [valentinavolgina2/sunny-hikes#3]
set server date to Pacific Time

**Comment by ybalenko** [comment]
I do not know whether it should be here or in a separate issue:
1)  the weather forecast displays Today with a shift in future time (for me, it's tomorrow).
2) when the user selects 'Today' on a calendar and clicks on 'Find', automatically yesterday is displayed. Timeshift into the past?

Let me know if we need separate issues for these cases.

**Comment by valentinavolgina2** [comment]
It's the server date issue. 1. and 2. are both belong to the same problem.  The server is on East Coast and 3 hours ahead. I'll fix it.

**Comment by valentinavolgina2** [comment]
Fixed
