### ISSUE TITLE
Sign in: add 'Forgot password?'

### ISSUE THREAD

**Issue by ybalenko** [valentinavolgina2/sunny-hikes#34]
I assume it's nice to have the 'Forgot password?' dialogue displayed on the 'Sign In' page.
Below, I attached an example.

Note: If we do not have 'Forgot password' functionality to be implemented in our plans, let's display a notification somewhere (e.g. you won't have a chance to restore your password in this release or etc.).

![example](https://user-images.githubusercontent.com/58673729/114245877-286e2680-9946-11eb-8750-635b62bb932f.png)

**Comment by valentinavolgina2** [comment]
done
