### ISSUE TITLE
[Low priority][Cosmetic] Update 'Welcome to website' text

### ISSUE THREAD

**Issue by ybalenko** [valentinavolgina2/sunny-hikes#4]
Steps:
1. Go to https://warm-river-49749.herokuapp.com/
2. Click on Register
3. Fill in Sign Up form
4. Click on Register

Actual result: The user gets 'Welcome to Nafanya website! "
Expected result: The user gets " Welcome to Seattle ☼ Seekers website!"

![IMG-01](https://user-images.githubusercontent.com/58673729/107604007-7fc07680-6be3-11eb-938f-22e48429704c.png)

**Comment by valentinavolgina2** [comment]
Fixed
