### ISSUE TITLE
[Cosmetic] Facilities, Activities: list of options ends with comma

### ISSUE THREAD

**Issue by ybalenko** [valentinavolgina2/sunny-hikes#40]
While creating a new recreation, a user chooses options. If a user selects more than one option for Facilities or/and Activities, we display a comma at the end of a list.

![IMG_9076](https://user-images.githubusercontent.com/58673729/117344467-430ac100-ae5a-11eb-8d57-7cbf61e420d7.jpeg)

**Comment by valentinavolgina2** [comment]
Fixed

**Comment by ybalenko** [comment]
The design was changed. The issue does not exist anymore.
