### ISSUE TITLE
[Cosmetic] Recreation label on a map - remove a cursor focus as a blue frame

### ISSUE THREAD

**Issue by ybalenko** [valentinavolgina2/sunny-hikes#41]
Environment:
Desktop and mobile versions: Chrome, Safari
**Firefox is OK! (see the last picture)**

When a user clicks on a map item, the recreation title is focused with a blue frame.

![IMG_9077](https://user-images.githubusercontent.com/58673729/117345927-f922da80-ae5b-11eb-8956-5d8a7fcb978f.jpeg)

![FF](https://user-images.githubusercontent.com/58673729/117346028-12c42200-ae5c-11eb-8b8e-ee8438f1bedc.png)

**Comment by valentinavolgina2** [comment]
fixed
