### ISSUE TITLE
[Cosmetic] Name in browser tab title differs from name on a logo.

### ISSUE THREAD

**Issue by ybalenko** [valentinavolgina2/sunny-hikes#42]
Browsers: Safari, Chrome

Actual result: The name in a browser tab -  'Seattle Sunny Seekers', the name on a logo - 'Seattle sun seekers'.
Expected result: The names are identical.

![Screenshot ](https://user-images.githubusercontent.com/58673729/118749899-45362d80-b813-11eb-9c85-6c97ddc3c64d.png)

**Comment by valentinavolgina2** [comment]
Fixed

**Comment by ybalenko** [comment]
Verified.
