### ISSUE TITLE
Error while submitting a comment

### ISSUE THREAD

**Issue by ybalenko** [valentinavolgina2/sunny-hikes#43]
Prerequisites:
Logged in as a user

Steps:
1. Go to Recreations
2. Select any recreation
3. Type a comment, press Submit
**Actual result:** A user can't see a comment while being logged in. 
An error is displayed in a Dev Tool browser console: 
20:21:42.803 loadMore.js:53 Uncaught TypeError: review.owner.equals is not a function
    at createdBody (loadMore.js:53)
    at createReviewCard (loadMore.js:77)
    at loadMoreComments (loadMore.js:98)
    at loadComments (loadMore.js:125)
    at loadMore.js:134
createdBody @ loadMore.js:53
createReviewCard @ loadMore.js:77
loadMoreComments @ loadMore.js:98
loadComments @ loadMore.js:125
(anonymous) @ loadMore.js:134

![error](https://user-images.githubusercontent.com/58673729/120426512-19dc3400-c325-11eb-8465-355bb937c25f.png)

**Comment by valentinavolgina2** [comment]
Fixed

**Comment by ybalenko** [comment]
Verified.
