### ISSUE TITLE
Bad request on creating a new recreation

### ISSUE THREAD

**Issue by ybalenko** [valentinavolgina2/sunny-hikes#45]
Preconditions:
Logged in as a user

Steps:
1. Got to recreations
2. Create new
3. Type name, select a place
4. Click on Create
**Actual result:** Get an error in console: POST https://warm-river-49749.herokuapp.com/hikes 400 (Bad Request)
On a page, the user gets: "hike.title" is not allowed.
**Expected result:** A new recreation is created.

![400](https://user-images.githubusercontent.com/58673729/121296998-764fce00-c8a6-11eb-9b2c-dcde1e916bb4.png)

**Comment by valentinavolgina2** [comment]
fixed
