### ISSUE TITLE
Activity: remove highlighting for a category

### ISSUE THREAD

**Issue by ybalenko** [valentinavolgina2/sunny-hikes#46]
Env.: web browsers (Chrome, MS Edge, Safari, etc.
Steps:
1. Go to https://warm-river-49749.herokuapp.com/hikes
2. Click on Activity
3. Click on any category title
Actual result: A category is highlighted, but not selected.
Expected result: Remove highlighting since we do not have an option for multiple selection of all subcategories.

![Screenshot ](https://user-images.githubusercontent.com/58673729/122259767-5a8c8f00-ce87-11eb-9f8c-2c5fcf0302e6.png)

**Comment by valentinavolgina2** [comment]
done
