### ISSUE TITLE
[Web] Add "Clear" for Facility and Activity categories

### ISSUE THREAD

**Issue by ybalenko** [valentinavolgina2/sunny-hikes#47]
Steps:

1. Go to https://warm-river-49749.herokuapp.com/hikes
2. Click on Activity/Facility
3. Select multiple subcategories

Actual result: As a user, if I want to unselect subcategories, I have to undo them one by one.
Expected result: Have an option to clear the specified filter by clicking on 'Clear'

**Comment by valentinavolgina2** [comment]
done
