### ISSUE TITLE
[Cosmetic] Good to know: update notification.

### ISSUE THREAD

**Issue by ybalenko** [valentinavolgina2/sunny-hikes#48]
Steps:
1. Go to the Recreations page
2. Click on Add new
3. Fill in the required fields(title, location)
4. Add smth to 'Good to know' section
5. Click on 'Add recreation'

Actual result: A user gets a notification: 'Successfully updated description!'
Expected result: A user gets a notification: 'Successfully updated Good to Know information!

Note: the same for editing this section.

**Comment by valentinavolgina2** [comment]
done
