### ISSUE TITLE
[Login/Registration] Email address should be removed from confirmation notification.

### ISSUE THREAD

**Issue by ybalenko** [valentinavolgina2/sunny-hikes#49]
Steps:
1. Go to new prod https://www.seattlesunseeker.com/login
2. Type Username and Password into the corresponding fields
3. Click on Login button

**Actual result:** The user gets the following message: "Your registration has not been confirmed. A link to activate your account has been sent to XXXX@XXXX (the real email address is hidden) and should be arriving shortly. If it doesn't arrive in your inbox, check your spam folder."

**Expected result:** It's really bad practice to display an email like this. It should not be displayed at all,  or it might be displayed partially. 

![Screenshot ](https://user-images.githubusercontent.com/58673729/128791100-922e55b0-c792-44f3-9b17-84729eb2fe39.png)

**Comment by valentinavolgina2** [comment]
done
