### ISSUE TITLE
[Low priority] Handle 'location should not be empty' more user-friendly.

### ISSUE THREAD

**Issue by ybalenko** [valentinavolgina2/sunny-hikes#5]
Steps:

1. Go to https://warm-river-49749.herokuapp.com/
2. Login
3. Recreations -> Create New
4. Type title name
5. Click on 'Add recreation'

Actual result: The user stays on the page and gets an error message that the location should not be empty. 
Expected result:  The user lost the data and get an error "hike.location" is not allowed to be empty.

![01](https://user-images.githubusercontent.com/58673729/107741108-5fff8000-6cc1-11eb-8be5-0b5d41b366f6.png)

**Comment by valentinavolgina2** [comment]
Hm, interesting. I worked before, but probably when I added a placeholder to the location field, smth stopped working. I'll look at it

**Comment by valentinavolgina2** [comment]
Fixed
