### ISSUE TITLE
[Directions] Editing location on a map does not automatically update a location field.

### ISSUE THREAD

**Issue by ybalenko** [valentinavolgina2/sunny-hikes#51]
Preconditions:
Registered user

Steps:
1. Go to https://www.seattlesunseeker.com/hikes
2. Select a recreation 
3. Click on a pencil to update a direction
4. On a map, move a pin to another location
5. Click on the Save button for the Directions section 

Expected result: The address will be auto-updated with the new location.
Actual result: A pin is saved on a map, but the address in a location field does not change.

**Comment by valentinavolgina2** [comment]
Won't be fixed. It's supposed to be this way. I can't figure out the location address by coordinates on the map.
The behavior is the following: choose the location, if the pointer should be moved to be more precise with the location, move it.
