### ISSUE TITLE
[Profile] sub-menu text disappears while clicking on it

### ISSUE THREAD

**Issue by ybalenko** [valentinavolgina2/sunny-hikes#56]
Environment:
https://seattlesunseeker-test.herokuapp.com
Browsers: latest Ms Edge, latest Safari

Steps:

1. Go to the website page
2. Click on Log in, type username and password, click on the Login button
3. Click on a profile menu and select any submenu (e.g. Messages)

Actual result: Sub-menu text disappears while clicking on it
Expected result: sub-menu should be available and visible.

![submenu](https://user-images.githubusercontent.com/58673729/133018246-1781f4e8-8db1-4ad4-96c1-e2247db8494f.png)

**Comment by valentinavolgina2** [comment]
Fixed

**Comment by ybalenko** [comment]
Verified.
