### ISSUE TITLE
[Join today] logged-in user gets register page

### ISSUE THREAD

**Issue by ybalenko** [valentinavolgina2/sunny-hikes#58]
Environment
https://seattlesunseeker-test.herokuapp.com

Steps:

1. Go to the website
2. Click on 'Log in', type username and password, click on the Login button
3. Click on the Home menu
4. Click on the Join today link in 'Want to be one of us? Join today, it’s free and fun!'

Actual result: Logged-in user gets Register page.
Expected result: TBD

![join](https://user-images.githubusercontent.com/58673729/133020560-0ea42022-42f0-4ed7-abc7-a06c664048d0.png)

**Comment by valentinavolgina2** [comment]
Fixed

**Comment by ybalenko** [comment]
Verified.
