### ISSUE TITLE
[Click here to log in] logged-in user gets login page

### ISSUE THREAD

**Issue by ybalenko** [valentinavolgina2/sunny-hikes#59]
Environment
https://seattlesunseeker-test.herokuapp.com

Steps:

1. Go to the website
2. Click on 'Log in', type username and password, click on the Login button
3. Click on the Home menu
4. Click on the Join today link in 'Want to be one of us? Join today, it’s free and fun!'
5. Click on 'click here to log in'

Actual result: Logged-in user gets login page.
Expected result: TBD

![login](https://user-images.githubusercontent.com/58673729/133020842-8df52f8d-9742-4f57-87bf-55ca71bacb60.png)

**Comment by valentinavolgina2** [comment]
Fixed

**Comment by ybalenko** [comment]
Verified.
