### ISSUE TITLE
[Cosmetic] Change 'recommendation' to 'recreation' in the notifications

### ISSUE THREAD

**Issue by ybalenko** [valentinavolgina2/sunny-hikes#6]
Steps:
Create/Update/Remove a recreation

**Actual result:** User gets 'Successfully made a new recommendation!' / 'The recommendation has been deleted!' / Successfully updated the recommendation!
**Expected result:** User gets 'Successfully made a new recreation!' / 'The recreation has been deleted!'/ 'The recreation has been updated!'

TBD

**Comment by valentinavolgina2** [comment]
Fixed
