### ISSUE TITLE
[Recreations] drop-down lists have double controls.

### ISSUE THREAD

**Issue by ybalenko** [valentinavolgina2/sunny-hikes#60]
Environment
https://seattlesunseeker-test.herokuapp.com
Latest browsers: Chrome, Safari

Steps:

1. Go to the website
2. Click on recreations

Actual result: On the recreations page, drop-down lists have double controls (2 arrows).
Expected result: Drop-down lists have a single control.

![control](https://user-images.githubusercontent.com/58673729/133021267-c9713e03-af50-4c5e-9489-352413f46158.png)

**Comment by valentinavolgina2** [comment]
Fixed

**Comment by ybalenko** [comment]
Verified.
