### ISSUE TITLE
[Safari] Blue frame over profile while clicking on a drop-down list

### ISSUE THREAD

**Issue by ybalenko** [valentinavolgina2/sunny-hikes#62]
Environment
https://seattlesunseeker-test.herokuapp.com
Latest browser: Safari (only)

Steps:

1. Go to the website as a logged-in user
2. Click on profile

Actual result: Blue frame over profile while clicking on a drop-down list. see picture
Expected result: Ther should not be a blue frame.

![frame](https://user-images.githubusercontent.com/58673729/133027353-542d136e-76e1-48c6-a2eb-a94178406de9.png)

**Comment by valentinavolgina2** [comment]
Fixed
