### ISSUE TITLE
[Edge][Chrome] different font for profile sub-menus 

### ISSUE THREAD

**Issue by ybalenko** [valentinavolgina2/sunny-hikes#63]
Environment:
https://seattlesunseeker-test.herokuapp.com
Browsers: latest MS Edge, latest Chrome

Steps:

1. Go to the website page as a logged-in user
2. On a home page, click on a profile menu to see sub-menus
3. On the hikes page, click on a profile menu to see sub-menus

Actual result: Sub-menu font is different (bold-ish for home page). See picture.
Expected result: Sub-menu font should be identical.

![font](https://user-images.githubusercontent.com/58673729/133341521-2dcb9b91-2ff4-416e-b31d-63781641a86b.png)

**Comment by valentinavolgina2** [comment]
Fixed
