### ISSUE TITLE
[Description] description with max allowed characters (1000 of 1000) leads to an error

### ISSUE THREAD

**Issue by ybalenko** [valentinavolgina2/sunny-hikes#67]
Steps:
1. Go to https://seattlesunseeker-test.herokuapp.com/hikes/
2. Select a particular recreation
3. Click on Description and enter text with max allowed symbols
4. Click on Suggest

Characters  1000 of 1000 below:

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pellentesque mauris in quam tempor, in elementum augue vulputate. Suspendisse vestibulum velit arcu, at interdum est aliquam eget. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed interdum lacus vel ullamcorper dapibus. In hac habitasse platea dictumst. Vivamus accumsan eleifend magna id pharetra. Curabitur imperdiet tortor nec dictum ultrices. Proin et velit in arcu mattis lacinia. Mauris id ornare felis, non sagittis arcu. Nulla facilisis neque vitae sem elementum, dignissim ultrices justo dapibus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec eu lectus eros. Sed in lacinia libero. Nulla facilisi.
Quisque quis orci porttitor, porttitor eros eget, consequat nunc. Suspendisse a sollicitudin ante. Donec mollis elit nisi, et dapibus mauris imperdiet at. Ut fringilla molestie cursus. Suspendisse finibus eget metus vitae congue. Pellentesque condimentum iaculis vel.

Expected result: Description with max allowed characters was added.
Actual result: User gets an error '"hike.description" length must be less than or equal to 1000 characters long'

**Comment by valentinavolgina2** [comment]
fixed
