### ISSUE TITLE
Recreations: selecting miles and pressing Find, affects current date

### ISSUE THREAD

**Issue by ybalenko** [valentinavolgina2/sunny-hikes#8]
Steps:

1. Go to the Home page
2. Click on 'Recreations'
3. On your right, select '10 miles' and click on 'Find'
4. Observe a current date
5. Repeat steps 3-4

Actual result: A current date (2021-02-18) changes automatically in a decremental way.
Expected result: A current date stays as is.

https://user-images.githubusercontent.com/58673729/108416281-560adf00-71e3-11eb-9887-09cad33f855a.mp4

**Comment by valentinavolgina2** [comment]
:) interesting. I don't have this error when I run website locally. I suspect it's a time zone problem. I'll look at it.
